### ISSUE TITLE
[v3] Organizer does not show non-ASCII text correctly.

### ISSUE THREAD

**Issue by aleksejrs** [luoliyan/incremental-reading#47]

**Comment by luoliyan** [comment]
In version v3, I assume?

I'll have a look at it.

**Comment by aleksejrs** [comment]
Yes, that's what the "[v3]" in the title means.

**Comment by TimotheeChauvin** [comment]
So that's what it meant! I kept thinking it referred to Belize's International Telecommunications Union callsign prefix all along! I have to say it makes a lot more sense now.

**Comment by luoliyan** [comment]
This should be fine now. Let me know.
