### ISSUE TITLE
Highlights should not be saved when the note creation is cancelled

### ISSUE THREAD

**Issue by TimotheeChauvin** [luoliyan/incremental-reading#52]
When extracting a portion of text or creating a flashcard with text selected, the highlight should only be saved if the extract or flashcard is added, not if it's closed without saving.

**Comment by luoliyan** [comment]
True.

At the moment, it can be undone with `u`, but I agree that shouldn't be necessary.

**Comment by luoliyan** [comment]
Fixed.
