### ISSUE TITLE
Fail to create extract

### ISSUE THREAD

**Issue by aronneagu** [luoliyan/incremental-reading#57]
Heya,

I have imported the following article https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html, using Alt+3. I have opened it in, selected the text "Amazon Resource Names (ARNs) uniquely identify AWS resources" (first sentence), pressed x and got the following error message:

```
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.0beta36 Python 3.6.1 Qt 5.9.2 PyQt 5.9
Platform: Mac 10.12.6
Flags: frz=True ao=True        

Caught exception:
  File "/Users/aron.neagu/Library/Application Support/Anki2/addons21/1081195335/text.py", line 57, in create
    did = mw.col.decks.byName(self.settings['extractDeck'])['id']
<class 'TypeError'>: 'NoneType' object is not subscriptable
```

Anki Version 2.1.0beta36
Incremental reading version 4.7.14
MacOS 10.12.6

I hope that all the bug reports will make the addon more amazing.

Kind regards,
Aron

**Comment by luoliyan** [comment]
Your destination deck for extracts doesn't exist any more.

Obviously the add-on should handle this situation more gracefully, but for now you just to change the destination deck to something that exists.

**Comment by luoliyan** [comment]
Fixed.
