### ISSUE TITLE
Error when creating a new flashcard from an extract

### ISSUE THREAD

**Issue by JJChill** [luoliyan/incremental-reading#68]
Debug info:
Anki 2.1.0beta36 Python 3.6.1 Qt 5.9.2 PyQt 5.9
Platform: Windows 10
Flags: frz=True ao=True        

Caught exception:
  File "C:/Users/Jevon/AppData/Roaming/Anki2\addons21\1081195335\main.py", line 169, in createNote
    addCards.editor.setNote(newNote)
  File "aqt\editor.py", line 293, in setNote
  File "aqt\editor.py", line 308, in loadNote
  File "anki\media.py", line 254, in escapeImages
  File "C:\Users\dae\AppData\Local\Programs\Python\Python36-32\lib\re.py", line 191, in sub
<class 'TypeError'>: expected string or bytes-like object

This happens when I use the shortcut that I defined as below:
![image](https://user-images.githubusercontent.com/4022309/36412349-99e2a898-1665-11e8-8b24-2136e99936ed.png)

**Comment by luoliyan** [comment]
Please try deleting the add-on and reinstalling it. That error message doesn't make a lot of sense, since there is not code at line 169 in the current version.

**Comment by JJChill** [comment]
I did as you said but it looks like it's still pulling down the same code. I get the same error and I can see that main.py does not match the main.py on GitHub. I verified that the add-on was deleted before re-downloading. Does Anki cache an add-on download or anything?

**Comment by luoliyan** [comment]
Sorry, it didn't occur to me that you're using the version on AnkiWeb.

Download the development version ([here](https://github.com/luoliyan/incremental-reading/archive/master.zip)) and drop the files from `ir` into `1081195335`, overwriting the existing ones.

Let me know if that fixes the issue.
