### ISSUE TITLE
v3.8.3 removes v4.9's QuickKey settings

### ISSUE THREAD

**Issue by aleksejrs** [luoliyan/incremental-reading#71]
When I start Anki 2.0, "Your Incremental Reading settings file has been modified for compatibility reasons. …", and my custom QuickKey is not there when I start Anki 2.1 after that.

**Comment by luoliyan** [comment]
QuickKeys are not compatible between v3 and v4. It might make sense to have separate `_ir.json` files for each major version, and I'll look into that when I have time. But for the time being, this is expected behaviour.

**Comment by tvhong** [comment]
Closing this issue as it has been 4 years.
