### ISSUE TITLE
Suggestion: paste Source to Field

### ISSUE THREAD

**Issue by aronneagu** [luoliyan/incremental-reading#73]
Hello there,

I was wondering if its possible to have another option in the config window -> Quick Keys, similar to "**Paste Text into Field**" that reads "**Paste Source into Field**". I would like to have in my flashcards also the source from where I took the information.
 
In the 20 Rule of formulating knowledge, one of the rules mentions that you should be able to trace back a piece of knowledge to its source. I have the problem that once I read an article online, and convert it to flashcards, ifIi encounter it again at some point in the future, how will I know if I already processed it?

Kind regards,
Aron

Image below for where the option would be:
<img width="777" alt="screen shot 2018-03-02 at 20 24 36" src="https://user-images.githubusercontent.com/1262715/36920224-eb416a7c-1e57-11e8-933c-39336f426fff.png">

**Comment by aleksejrs** [comment]
There is such option in version 4: https://github.com/luoliyan/incremental-reading/commit/7d0dedaffdfe9bba14af901af3523f92cfe40310

**Comment by aronneagu** [comment]
Awesome. Thanks a lot for that :)
