### ISSUE TITLE
DATALOSS: switching priorities scheduler on/off loses cards that are in filtered decks.

### ISSUE THREAD

**Issue by aleksejrs** [luoliyan/incremental-reading#76]
1. Make a filtered deck that takes cards out of the IR deck.
2. Switch priorities mode on or off, which changes the note type of the IR cards.

The cards that were in the filtered deck are just lost.

**Comment by luoliyan** [comment]
When I try to replicate this, the cards are removed from the filtered deck, but they remain in the collection. Is that what you mean?

**Comment by luoliyan** [comment]
I've tried this in a few different ways. When I switch priorities mode on or off, the filtered cards return to their home deck.

**Comment by luoliyan** [comment]
If you manage to replicate this with an up-to-date install with other add-ons disabled, let me know the steps and I'll take another look at it.
