### ISSUE TITLE
<class 'KeyError'>: 'extractDeck' after post-install restart of Anki

### ISSUE THREAD

**Issue by slavistan** [luoliyan/incremental-reading#77]
Starting Anki after installing IR pops up the following error which persists after reinstalling of Anki and IR including the deletion of the add-ons folder. No other add-ons are used. 

**Anki Version:** Version 2.1.0beta37, Qt 5.9.2 PyQt 5.9
**IR Version:** v4.9.11
**Windows 10**

---

### Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.0beta37 Python 3.6.1 Qt 5.9.2 PyQt 5.9
Platform: Windows 10
Flags: frz=True ao=True        

```
Caught exception:
  File "aqt\progress.py", line 67, in handler
  File "aqt\main.py", line 120, in setupProfile
  File "aqt\main.py", line 261, in loadProfile
  File "anki\hooks.py", line 28, in runHook
  File "C:/Users/Stan/AppData/Roaming/Anki2\addons21\1081195335\main.py", line 60, in onProfileLoaded
    self.loadMenuItems()
  File "C:/Users/Stan/AppData/Roaming/Anki2\addons21\1081195335\main.py", line 103, in loadMenuItems
    self.settings.loadMenuItems()
  File "C:/Users/Stan/AppData/Roaming/Anki2\addons21\1081195335\settings.py", line 188, in loadMenuItems
    settings['extractDeck'])
<class 'KeyError'>: 'extractDeck'
```
---

Attempting to use Anki with IR causes further errors, such as

```
<class 'AttributeError'>: 'ReadingManager' object has no attribute 'shortcuts'
```

**Comment by luoliyan** [comment]
Let me know if this is still happening with the current version.

If it is, see if removing `_ir.json` from `collection.media` makes any difference.
