### ISSUE TITLE
plugin disappeared from ankiweb

### ISSUE THREAD

**Issue by edwintorok** [luoliyan/incremental-reading#80]
https://ankiweb.net/shared/info/1081195335 says "This shared item is no longer available."

**Comment by aleksejrs** [comment]
→ https://anki.tenderapp.com/discussions/ankiweb/3214-restore-luoliyans-account

**Comment by UsernameIsAlreadyTaken6** [comment]
inb4 archiving

Anyway, thanks for your contribution @luoliyan.

**Comment by aleksejrs** [comment]
(Damien wrote at the link I mentioned above: "Shared add-ons do not expire, so the author must have removed the item or their account.")

**Comment by luoliyan** [comment]
Sorry folks. That was accidental. It's up again.

**Comment by glutanimate** [comment]
@luoliyan Awesome! Glad to have you back. FWIW, you might be able to ask Damien to reassign the AnkiWeb listing the old ID. That way backlinks pointing to the old page would still work. Perhaps he might even be able to reinstate some of the old reviews.
