### ISSUE TITLE
"Import Pocket" not working

### ISSUE THREAD

**Issue by AlexZHENGH** [luoliyan/incremental-reading#82]
The add-on works perfectly for importing web pages using urls; however, importing from Pocket does not work for me, each time raising an error:

```
Caught exception:
  File "/Users/username/Library/Application Support/Anki2/addons21/935264945/importer.py", line 215, in importPocket
    for a in response.json()['list'].values()]
<class 'AttributeError'>: 'list' object has no attribute 'values'
```

The authorisation was successful because I could find it in https://getpocket.com/connected_applications.

**Specs:**
- Anki 2.1.5 Python 3.6.1 Qt 5.9.2 PyQt 5.9
- Platform: Mac 10.14.1
- Flags: frz=True ao=True sv=1
- Incremental Reading Version v4913

**Comment by AlexZHENGH** [comment]
After I removed the authorisation, restarted Anki, and reconnected to Pocket, it worked now.

**Comment by luoliyan** [comment]
Thanks for the report, though. Let me know if anything else stops working.
