### ISSUE TITLE
import cgi (anki beta)

### ISSUE THREAD

**Issue by khonkhortisan** [luoliyan/incremental-reading#87]
**Describe the bug**
Mod doesn't load, errors on importing cgi from feedparser

**To Reproduce**
Use anki-2.1.6-beta1-windows.exe or anki-2.1.6-beta2-windows.exe ?

**Expected behavior**
```
# ---------- required modules (should come with any Python distribution) ----------
import cgi
```
It should work, as the comment says.

**Screenshots**
![image](https://user-images.githubusercontent.com/1996449/49424930-f2ef1800-f750-11e8-95af-63eda3b6e132.png)
```
---------------------------
Anki
---------------------------
Una extensión que has instalado ha fallado al cargarse. Si los problemas persisten, por favor ve a Herramientas> Menú de extensiones o deshabilita esta extensión.

Mientras cargando 'Incremental Reading v4913':
Traceback (most recent call last):
  File "aqt\addons.py", line 60, in loadAddons
  File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\935264945\__init__.py", line 17, in <module>
    from .main import ReadingManager
  File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\935264945\main.py", line 28, in <module>
    from .importer import Importer
  File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\935264945\importer.py", line 43, in <module>
    from .lib.feedparser import parse
  File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\935264945\lib\feedparser.py", line 133, in <module>
    import cgi
ModuleNotFoundError: No module named 'cgi'


---------------------------
Aceptar   
---------------------------
```

**Specs (please complete the following information):**
 - OS: Windows 10 1803 SO 17134.407
 - anki-2.1.6-beta1-windows.exe and anki-2.1.6-beta2-windows.exe 
- Incremental Reading v4.9.13 https://ankiweb.net/shared/info/935264945

**Additional context**
Without that comment above the import, I would assume I would have to install a python module on windows.
It's probably that 2.1.6 changed how it sets up the python path or loads addons.

**Comment by luoliyan** [comment]
Thanks, I'll look into this tomorrow and bundle `cgi` if I need to.

**Comment by luoliyan** [comment]
This should be fixed now thanks to Morgan.
