### ISSUE TITLE
Documentation is confusing re: how to import a webpage

### ISSUE THREAD

**Issue by ckp95** [luoliyan/incremental-reading#93]
> Experimentation should lead to a pretty quick understanding of how the add-on works. If in doubt, start with the following:

>Create a new IR note with an article you want to study (the easiest way to do this is to import a webpage, with Alt+3)

I got stuck on this for half an hour. I thought you had to press Alt-3 from the note creation interface and I got confused and frustrated when nothing happened. I didn't realise you had to do it from the deck interface. This should be reworded imo, especially since this is literally the only documentation for the addon (the link to the old documentation is broken, too).

**Comment by aleksejrs** [comment]
> (the link to the old documentation is broken, too).

Something happened to `https://htmlpreview.github.io/?`. Remove that part and you'll have "https://github.com/aleksejrs/anki-2.0-vsa-and-ire/blob/for_everyone/doc/View_Size_Adjust_and_Incremental_Reading_Extension_addons_-_Google_Groups.html" which works but gives you an HTML file you have to download or copy into another viewer.

**Comment by luoliyan** [comment]
I'll update the readme to clear up the confusion.

As for the old Google Groups readme, you can view it here for now: https://luoliyan.github.io/incremental-reading
